name: textractor-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pytest
  - sqlalchemy
  - pyodbc
  - regex
  - pandas
  - numpy
  - fastapi
  - owlready2
  - rdflib
  - flashtext
  - lemminflect
  - pyaml
  - owlready2
  - pip
  - pip:
    - textacy[all]
    - spacy >= 3
    - quickumls
    - negspacy
    - extractacy
